### ISSUE TITLE
Could you specify this component license?

### ISSUE THREAD

**Issue by b4-tahayashi** [A1rPun/vue-quick-edit#1]
I would like to use this component. But the license is not specified and can not be introduced.
please specify license?

**Comment by A1rPun** [comment]
Hey @b4-tahayashi, thanks for letting me know. Fixed in commit d2e1fba. In the package.json there was ISC licence specified but I changed this to the intended MIT licence.

The Licence will get published to NPM when there are more features to push :). Which will be this week.

**Comment by b4-tahayashi** [comment]
Thank you for support!😺
