### ISSUE TITLE
input 0 length value doesn't trigger any event

### ISSUE THREAD

**Issue by softengineer** [A1rPun/vue-quick-edit#11]
trying to edit a value, input 0 lenght value, the component can show EMPTY text, however, component doesn't trigger any event like input / raw-input / close in this case, only input non 0 length value can trigger these events. I try version 1.3.0

**Comment by A1rPun** [comment]
Thanks for your issue, I'll look into this.

**Comment by A1rPun** [comment]
I checked this in 1.3.0 and have no issues with empty values not triggering events. I updated the examples to `console.log` with useful info this time around.
