### ISSUE TITLE
Problem with everythin "Empty"

### ISSUE THREAD

**Issue by yuristru** [A1rPun/vue-quick-edit#12]
Hi, i just included the raw .min.js and tried this:

<quick-edit type="input" button-ok-text="Done!" empty-text="sdfsd" v-model="invoice.project_name"><quick-edit>

The "Done!"-Button is rendered corretly but all my values are shown as "Empty". Even with or without setting empty-text. But editing works and when i start editing the field has the correct value of invoice.project_name.

Any ideas?

best regards, Yuri

**Comment by A1rPun** [comment]
Thanks for your issue, I'll look into this.

**Comment by A1rPun** [comment]
I can't reproduce the issue, can you please provide the configuration you use? I'm not sure in what context `invoice.project_name` is used.

**Comment by yuristru** [comment]
Fixed it by using recomended import method and not including the min.js
