### ISSUE TITLE
Use the blur  event to save text automatically on blur

### ISSUE THREAD

**Issue by slidenerd** [A1rPun/vue-quick-edit#16]
Fantastic work with this library first of all

- I tried using it in inside a bulma table and i saw something weird, 
- Click on a column, in toggles into edit mode, 
- click on another column it also toggles into edit mode.
- you end up with a bunch of input fields and all of them are editable
- in my opinion you should use the blur event to change the field back to div once the input field doesnt have focus anymore
- thank you for taking time to read my issue

**Comment by A1rPun** [comment]
Thanks for your kind words and issue.
You are right this could be nice, it was even a feature in a previous version but I decided to remove it.
