### ISSUE TITLE
how validate before click success button?

### ISSUE THREAD

**Issue by drinsorz** [A1rPun/vue-quick-edit#17]
Hi, it's possible to validate on the button's onclick before hiding the input? 
![image](https://user-images.githubusercontent.com/20526106/127093898-7d113268-4a41-433f-ad10-a516c7626e6b.png)

**Comment by A1rPun** [comment]
Hey, thanks for the issue.
You can add a `:validator="validFn"` to `<vue-quick-edit>`. It will emit an `invalid` event (`@invalid="invalidFn"`) when the result of the `validFn` returns a **truthy** value.

```html
<quick-edit v-model="myValue" :validator="validFn" @invalid="invalidFn"></quick-edit>
```

```javascript
validFn: (value) => value.length < 3,
invalidFn: (error) => {
  if (error) {
    // do something
  }
},
```

I like the idea of having a custom slot for error messages.
