### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by mrgfrederic** [A1rPun/vue-quick-edit#6]
Hi, this question is probably stupid, but is there an property for adding a default selected value on options array for the select, checkbox input ?

![Capture](https://user-images.githubusercontent.com/42940842/69157058-b42eab00-0ae4-11ea-88e9-4fad4084761a.PNG)

Sorry for my bad english !

Thanks !

**Comment by A1rPun** [comment]
Hey, thanks for your question.

The intended way is adding a `v-model` to the quick-edit and set the value of the default option you want to show. Example:

The template:
```
<quick-edit
  v-model="textValue"
  :options="options"
></quick-edit>
```

and in your javascript:
```
export default {
  data() {
    return {
      textValue: 'fooValue',
      options: [
        { text: 'Foo', value: 'fooValue' },
        { text: 'Bar', value: 'barValue' },
        { text: 'Qux', value: 'quxValue' },
      ],
    };
  },
};
```

This will select the option you want, when you have `multiple` attribute set on your select you can pass an array to `v-model`. I hope this answers your question.

**Comment by A1rPun** [comment]
Closed due to inactivity
