### ISSUE TITLE
Clicking on cancel button doesn't actually cancel...

### ISSUE THREAD

**Issue by thoughtspacewebsites** [A1rPun/vue-quick-edit#8]
It just saves whatever value was typed in, same as the confirm button. This really gimps the current functionality of this component...

**Comment by kaishuu0123** [comment]
A similar problem was found.
The affected browser is Firefox. Does not occur in Chrome.

Guess that there is a problem with the order in which the `focusout` event occur.

**Comment by thoughtspacewebsites** [comment]
I've got this issue in Safari personally. Haven't tried this pull request. Does this address the issue on Safari too?

**Comment by kaishuu0123** [comment]
@thoughtspacewebsites 
Yes.  Tried in my PR. There was no problem with safari.

**Comment by A1rPun** [comment]
Thanks for your issue, I'll look into this and will check the PR.

**Comment by A1rPun** [comment]
Decided to scrap the auto-hide feature because it caused many bugs and confusion for the end-user.
